version: '3.8'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    volumes:
      - /volume1/docker/plex/config:/config:rw
      - /volume1/video/films:/data/films:ro
      - /volume1/video/series:/data/series:ro
      - /volume1/music:/data/music:ro
    restart: always
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TERM=xterm
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - CHANGE_CONFIG_DIR_OWNERSHIP=false
      - HOME=/config
      - TZ=Europe/Paris
      - HOSTNAME=${HOSTNAME}
      - LOCAL_NETWORK=${LOCAL_NETWORK}
      - PLEX_UID=${PLEX_UID}
      - PLEX_GID=${PLEX_GID}
      - PLEX_CLAIM=${PLEX_CLAIM}
    network_mode: bridge
    ports:
      - 32400:32400/tcp
      - :1900/udp
      - :8324/tcp
      - :32410/udp
      - :32412/udp
      - :32413/udp
      - :32414/udp
      - :32469/tcp
