version: '3.8'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    volumes:
      - ./config:/config:rw
      - /volume1/music:/data/music:ro
      - /volume1/video/films:/data/films:ro
      - /volume1/video/series:/data/series:ro
      - /volume1/video/animations:/data/animations:ro
      - /volume1/video/music-videos:/data/music-videos:ro
      - /volume1/photo:/data/photo:ro
    restart: always
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - CHANGE_CONFIG_DIR_OWNERSHIP=false
      - HOME=/config
      - TZ=Europe/Paris
      - HOSTNAME=${HOSTNAME}
      - ADVERTISE_IP=${URL}
      - LAN_NETWORK=${LAN_NETWORK}
      - ALLOWED_NETWORKS=${LAN_NETWORK}
      - PLEX_UID=${PLEX_UID}
      - PLEX_GID=${PLEX_GID}
      - PLEX_CLAIM=${PLEX_CLAIM}
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 10000M